    version: '3.8' 

    services:
      web:
        build: .
        image: ojhashish/python-app 
        expose:
          - "80"
        environment:
          FLASK_RUN_PORT: 80
        restart: always

      web2:
        build: .
        image: ojhashish/python-app
        expose:
          - "80"
        environment:
          FLASK_RUN_PORT: 80
        restart: always

      nginx:
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
          - "80:80" 
        depends_on:
          - web 
          - web2 
        restart: always
