- name: Deploy to EC2 instances and ensure ALB mounting
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  run: |
    echo "${{ secrets.EC2_HOSTS }}" | tr ' ' '\n' | while read host; do
      echo "Initiating deployment to EC2 instance: $host..."
      ssh -o StrictHostKeyChecking=no ec2-user@$host "bash -s" <<'ENDSSH'
        sudo systemctl start docker || sudo service docker start
        echo "Docker service ensured."

        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
        echo "Logged into Docker Hub on EC2."

        if [ $(docker ps -aq -f name=my-python-app) ]; then
          echo "Stopping and removing old container..."
          docker stop my-python-app || true
          docker rm my-python-app || true
        else
          echo "No existing container named 'my-python-app' found."
        fi

        echo "Pulling latest Docker image: ${DOCKER_USERNAME}/python-app:latest..."
        docker pull "${DOCKER_USERNAME}/python-app:latest"
        echo "Image pulled successfully."

        echo "Starting new container..."
        docker run -d -p 80:80 --name my-python-app "${DOCKER_USERNAME}/python-app:latest"
        echo "New container started."
      ENDSSH
    done

